[project]
name = "gsplat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"

[tool.ruff.lint]
select = ["I"]

[build-system]
build-backend = "setuptools.build_meta"
requires = ["torch", "setuptools >= 77.0.3", "ninja"]
